// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TravelGuideDbPart.Db;

#nullable disable

namespace TravelGuideDbTools.DbMigration.Migrations
{
    [DbContext(typeof(TravelGuideDbContext))]
    [Migration("20260916032014_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TravelGuideCore.Domain.CategoryModels.CategoryModel", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("TravelGuideCore.Domain.DistancesByPlaces.DistanceByPlace", b =>
                {
                    b.Property<int>("DistanceByPlaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DistanceByPlaceId"));

                    b.Property<int>("Distance")
                        .HasColumnType("int");

                    b.Property<int>("FromPointId")
                        .HasColumnType("int");

                    b.Property<int>("PlaceId")
                        .HasColumnType("int");

                    b.HasKey("DistanceByPlaceId");

                    b.HasIndex("FromPointId");

                    b.HasIndex("PlaceId", "FromPointId")
                        .IsUnique();

                    b.ToTable("DistanceByPlaces", (string)null);
                });

            modelBuilder.Entity("TravelGuideCore.Domain.FromPointModels.FromPointModel", b =>
                {
                    b.Property<int>("FromPointId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FromPointId"));

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("FromPointId");

                    b.HasIndex("LocationId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("FromPoints", (string)null);
                });

            modelBuilder.Entity("TravelGuideCore.Domain.LocationModels.LocationModel", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationId"));

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.HasKey("LocationId");

                    b.HasIndex("Latitude", "Longitude")
                        .IsUnique();

                    b.ToTable("Locations", (string)null);
                });

            modelBuilder.Entity("TravelGuideCore.Domain.MonthModels.MonthModel", b =>
                {
                    b.Property<int>("MonthId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MonthId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Months", (string)null);
                });

            modelBuilder.Entity("TravelGuideCore.Domain.MotorcycleModels.MotorcycleModel", b =>
                {
                    b.Property<int>("MotorcycleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MotorcycleId"));

                    b.Property<string>("Manufacturer")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MotorcycleKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<string>("StateNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MotorcycleId");

                    b.HasIndex("MotorcycleKey")
                        .IsUnique();

                    b.ToTable("Motorcycles", (string)null);
                });

            modelBuilder.Entity("TravelGuideCore.Domain.MunicipalityModels.MunicipalityModel", b =>
                {
                    b.Property<int>("MunicipalityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MunicipalityId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MunicipalityId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Municipalities", (string)null);
                });

            modelBuilder.Entity("TravelGuideCore.Domain.PlaceModels.PlaceModel", b =>
                {
                    b.Property<int>("PlaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlaceId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MunicipalityId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("RegionId")
                        .HasColumnType("int");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("UrlHashCode")
                        .HasColumnType("int");

                    b.HasKey("PlaceId");

                    b.HasIndex("MunicipalityId");

                    b.HasIndex("RegionId");

                    b.HasIndex("UrlHashCode");

                    b.ToTable("Places", (string)null);
                });

            modelBuilder.Entity("TravelGuideCore.Domain.PlacesByBestSeasons.PlaceByBestSeason", b =>
                {
                    b.Property<int>("PlaceId")
                        .HasColumnType("int");

                    b.Property<int>("MonthId")
                        .HasColumnType("int");

                    b.HasKey("PlaceId", "MonthId");

                    b.HasIndex("MonthId");

                    b.ToTable("PlacesByBestSeasons", (string)null);
                });

            modelBuilder.Entity("TravelGuideCore.Domain.PlacesByCategories.PlaceByCategory", b =>
                {
                    b.Property<int>("PlaceId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("PlaceId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("PlacesByCategories", (string)null);
                });

            modelBuilder.Entity("TravelGuideCore.Domain.PlacesByLocations.PlaceByLocation", b =>
                {
                    b.Property<int>("PlaceId")
                        .HasColumnType("int");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.HasKey("PlaceId", "LocationId");

                    b.HasIndex("LocationId");

                    b.ToTable("PlacesByLocations", (string)null);
                });

            modelBuilder.Entity("TravelGuideCore.Domain.PlacesByTags.PlaceByTag", b =>
                {
                    b.Property<int>("PlaceId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.HasKey("PlaceId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("PlacesByTags", (string)null);
                });

            modelBuilder.Entity("TravelGuideCore.Domain.RegionModels.RegionModel", b =>
                {
                    b.Property<int>("RegionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegionId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RegionId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Regions", (string)null);
                });

            modelBuilder.Entity("TravelGuideCore.Domain.RouteDistanceModels.RouteDistanceModel", b =>
                {
                    b.Property<int>("RouteDistanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RouteDistanceId"));

                    b.Property<double>("AirDistance")
                        .HasColumnType("float");

                    b.Property<int>("EndLocationId")
                        .HasColumnType("int");

                    b.Property<double>("RoadDistance")
                        .HasColumnType("float");

                    b.Property<TimeSpan>("RoadTime")
                        .HasColumnType("time");

                    b.Property<int>("StartLocationId")
                        .HasColumnType("int");

                    b.HasKey("RouteDistanceId");

                    b.HasIndex("EndLocationId");

                    b.HasIndex("StartLocationId", "EndLocationId")
                        .IsUnique();

                    b.ToTable("RouteDistances", (string)null);
                });

            modelBuilder.Entity("TravelGuideCore.Domain.TagModels.TagModel", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TagId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TagId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags", (string)null);
                });

            modelBuilder.Entity("TravelGuideCore.Domain.TaskModels.TaskModel", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskId"));

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TaskId");

                    b.HasIndex("TaskName")
                        .IsUnique();

                    b.ToTable("Tasks", (string)null);
                });

            modelBuilder.Entity("TravelGuideCore.Domain.TaskStartPoints.TaskStartPoint", b =>
                {
                    b.Property<int>("TspId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TspId"));

                    b.Property<string>("StartPoint")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.HasKey("TspId");

                    b.HasIndex("TaskId");

                    b.ToTable("TaskStartPoints", (string)null);
                });

            modelBuilder.Entity("TravelGuideCore.Domain.UrlGraphNodes.UrlGraphNode", b =>
                {
                    b.Property<int>("UgnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UgnId"));

                    b.Property<int>("FromUrlId")
                        .HasColumnType("int");

                    b.Property<int>("GotUrlId")
                        .HasColumnType("int");

                    b.HasKey("UgnId");

                    b.HasIndex("GotUrlId");

                    b.HasIndex("FromUrlId", "GotUrlId")
                        .IsUnique();

                    b.ToTable("UrlGraphNodes", (string)null);
                });

            modelBuilder.Entity("TravelGuideCore.Domain.VisitImages.VisitImage", b =>
                {
                    b.Property<int>("VisitImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VisitImageId"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<int>("VisitId")
                        .HasColumnType("int");

                    b.HasKey("VisitImageId");

                    b.HasIndex("VisitId", "FileName")
                        .IsUnique();

                    b.ToTable("VisitImages", (string)null);
                });

            modelBuilder.Entity("TravelGuideCore.Domain.VisitModels.VisitModel", b =>
                {
                    b.Property<int>("VisitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VisitId"));

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<int>("MotorcycleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("datetime");

                    b.HasKey("VisitId");

                    b.HasIndex("LocationId");

                    b.HasIndex("MotorcycleId");

                    b.ToTable("Visits", (string)null);
                });

            modelBuilder.Entity("TravelGuideCore.Domain.DistancesByPlaces.DistanceByPlace", b =>
                {
                    b.HasOne("TravelGuideCore.Domain.FromPointModels.FromPointModel", "FromPointNavigation")
                        .WithMany()
                        .HasForeignKey("FromPointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelGuideCore.Domain.PlaceModels.PlaceModel", "PlaceNavigation")
                        .WithMany("Distances")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromPointNavigation");

                    b.Navigation("PlaceNavigation");
                });

            modelBuilder.Entity("TravelGuideCore.Domain.FromPointModels.FromPointModel", b =>
                {
                    b.HasOne("TravelGuideCore.Domain.LocationModels.LocationModel", "LocationNavigation")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.Navigation("LocationNavigation");
                });

            modelBuilder.Entity("TravelGuideCore.Domain.PlaceModels.PlaceModel", b =>
                {
                    b.HasOne("TravelGuideCore.Domain.MunicipalityModels.MunicipalityModel", "MunicipalityNavigation")
                        .WithMany()
                        .HasForeignKey("MunicipalityId");

                    b.HasOne("TravelGuideCore.Domain.RegionModels.RegionModel", "RegionNavigation")
                        .WithMany()
                        .HasForeignKey("RegionId");

                    b.Navigation("MunicipalityNavigation");

                    b.Navigation("RegionNavigation");
                });

            modelBuilder.Entity("TravelGuideCore.Domain.PlacesByBestSeasons.PlaceByBestSeason", b =>
                {
                    b.HasOne("TravelGuideCore.Domain.MonthModels.MonthModel", "MonthNavigation")
                        .WithMany()
                        .HasForeignKey("MonthId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelGuideCore.Domain.PlaceModels.PlaceModel", "PlaceNavigation")
                        .WithMany("BestSeasons")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonthNavigation");

                    b.Navigation("PlaceNavigation");
                });

            modelBuilder.Entity("TravelGuideCore.Domain.PlacesByCategories.PlaceByCategory", b =>
                {
                    b.HasOne("TravelGuideCore.Domain.CategoryModels.CategoryModel", "CategoryNavigation")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelGuideCore.Domain.PlaceModels.PlaceModel", "PlaceNavigation")
                        .WithMany("Categories")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoryNavigation");

                    b.Navigation("PlaceNavigation");
                });

            modelBuilder.Entity("TravelGuideCore.Domain.PlacesByLocations.PlaceByLocation", b =>
                {
                    b.HasOne("TravelGuideCore.Domain.LocationModels.LocationModel", "LocationNavigation")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelGuideCore.Domain.PlaceModels.PlaceModel", "PlaceNavigation")
                        .WithMany("Locations")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LocationNavigation");

                    b.Navigation("PlaceNavigation");
                });

            modelBuilder.Entity("TravelGuideCore.Domain.PlacesByTags.PlaceByTag", b =>
                {
                    b.HasOne("TravelGuideCore.Domain.PlaceModels.PlaceModel", "PlaceNavigation")
                        .WithMany("Tags")
                        .HasForeignKey("PlaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelGuideCore.Domain.TagModels.TagModel", "TagNavigation")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlaceNavigation");

                    b.Navigation("TagNavigation");
                });

            modelBuilder.Entity("TravelGuideCore.Domain.RouteDistanceModels.RouteDistanceModel", b =>
                {
                    b.HasOne("TravelGuideCore.Domain.LocationModels.LocationModel", null)
                        .WithMany()
                        .HasForeignKey("EndLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TravelGuideCore.Domain.LocationModels.LocationModel", null)
                        .WithMany()
                        .HasForeignKey("StartLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelGuideCore.Domain.TaskStartPoints.TaskStartPoint", b =>
                {
                    b.HasOne("TravelGuideCore.Domain.TaskModels.TaskModel", "TaskNavigation")
                        .WithMany("StartPoints")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TaskNavigation");
                });

            modelBuilder.Entity("TravelGuideCore.Domain.UrlGraphNodes.UrlGraphNode", b =>
                {
                    b.HasOne("TravelGuideCore.Domain.PlaceModels.PlaceModel", null)
                        .WithMany()
                        .HasForeignKey("FromUrlId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TravelGuideCore.Domain.PlaceModels.PlaceModel", null)
                        .WithMany()
                        .HasForeignKey("GotUrlId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelGuideCore.Domain.VisitImages.VisitImage", b =>
                {
                    b.HasOne("TravelGuideCore.Domain.VisitModels.VisitModel", "VisitNavigation")
                        .WithMany("Images")
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VisitNavigation");
                });

            modelBuilder.Entity("TravelGuideCore.Domain.VisitModels.VisitModel", b =>
                {
                    b.HasOne("TravelGuideCore.Domain.LocationModels.LocationModel", null)
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TravelGuideCore.Domain.MotorcycleModels.MotorcycleModel", null)
                        .WithMany()
                        .HasForeignKey("MotorcycleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TravelGuideCore.Domain.PlaceModels.PlaceModel", b =>
                {
                    b.Navigation("BestSeasons");

                    b.Navigation("Categories");

                    b.Navigation("Distances");

                    b.Navigation("Locations");

                    b.Navigation("Tags");
                });

            modelBuilder.Entity("TravelGuideCore.Domain.TaskModels.TaskModel", b =>
                {
                    b.Navigation("StartPoints");
                });

            modelBuilder.Entity("TravelGuideCore.Domain.VisitModels.VisitModel", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
